### ISSUE TITLE
Model Files Format

### ISSUE THREAD

**Issue by yuizumi** [icfpcontest2018/icfpcontest2018.github.io#10]
What is the byte/bit order? For example, suppose (R = 8), then the voxel at (1, 2, 3) is represented at the bit 83 (= 1 × 8 × 8 + 2 × 8 + 3), but where is the bit 83 (in the 64-byte sequence)?

**Comment by MatthewFluet** [comment]
With `R = 8`, then coordinate `(1, 2, 3)` is indeed at bit `83`, which is bit `3 = 83 % 3` (ie, the bit with value `2^3`) of the byte at index `10 = 83 / 8` (which is the byte at index `11` of the whole file).

**Comment by yuizumi** [comment]
Thanks. Just to be crystal clear: I presume the byte index is counted from the head (beginning); am I right or is it from the tail?

**Comment by MatthewFluet** [comment]
Yes, from the beginning of the file.

**Comment by yuizumi** [comment]
Okay, thanks, very clear now!
