### ISSUE TITLE
SHA256 checksum intermittently failing on submission

### ISSUE THREAD

**Issue by tsemple** [icfpcontest2018/icfpcontest2018.github.io#11]
We are getting the error "Failure:: SHA256 checksum did not match" on the ack page. It looks a number of teams are hitting this. And it seems resubmitting sometimes fixes the issue. Is there a bug with this check?

This sequences looks like someone tried submitting with the correct sha, then the returned sha, then the correct sha again and succeed the second time.

20180720202523 | f7a18f0c94a8a1ff90e35a416a6c6a76199de01f21191ade7c9dee337acbc832 | Failure:: SHA256 checksum did not match: f7a18f0c94a8a1ff90e35a416a6c6a76199de01f21191ade7c9dee337acbc832 != 40d201f561608b3c99840019376c7df900bb2530b7662e6c2b974c6681c2fe29

20180720212601 | 40d201f561608b3c99840019376c7df900bb2530b7662e6c2b974c6681c2fe29 | Failure:: SHA256 checksum did not match: 40d201f561608b3c99840019376c7df900bb2530b7662e6c2b974c6681c2fe29 != e7a9adb5a7ae4329e4ad4e1bf095c1809878555b7f41e76bbd31b399d42cd5b7

20180720214407 | f7a18f0c94a8a1ff90e35a416a6c6a76199de01f21191ade7c9dee337acbc832 | Success

**Comment by tsemple** [comment]
I figured out my problem. I was using the google share link. I followed the instructions to change it to a google download link and that worked. So if anyone else is hitting this, you want a url like this:
https://drive.google.com/uc?id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by MatthewFluet** [comment]
Sounds like the issue has been resolved.

I'd like to change the title of the issue to "SHA256 checksum intermittently failing on submission", which I think better captures the issue (and will better serve anyone checking the list of closed issues).
