### ISSUE TITLE
When does a newly fissioned bot take an action?

### ISSUE THREAD

**Issue by undefinedvalue** [icfpcontest2018/icfpcontest2018.github.io#13]
The spec says that the new bot from a fission is added to the active set of bots. Does this new bot then perform a command, or does the command-assignment step happen as a single transaction before any commands have executed?

Also, would the new bot be counted in the total number of active bots "n" for the (20 * n) energy cost for the bots on the same step it was created?

**Comment by MatthewFluet** [comment]
The "new" bot at a fission does not get charged a per-bot step cost and does not perform a command in the step in which it was created.  The `n` is the number of active bots at the beginning of the time step.
