### ISSUE TITLE
Show time for last check on submission ack page

### ISSUE THREAD

**Issue by jandreske** [icfpcontest2018/icfpcontest2018.github.io#3]
It would be great if the submission acknowledgements page could show whether and when downloading submissions has been attempted, so that it is obvious whether a entry is missing because the download has not happened yet or because there were issues with accessing the uploaded file / verifying the shasum / unzipping the archive.

**Comment by MatthewFluet** [comment]
Yes, coming with the first submissions-ack refresh.
