### ISSUE TITLE
Well-formed state enforcement during a tick

### ISSUE THREAD

**Issue by lostmsu** [icfpcontest2018/icfpcontest2018.github.io#6]
Just wanted to clarify. Is there any sort of state enforcement between the beginning and the end of the turn?

E.g. how the following two situations should be resolved?
1. While `S.harmonics == Low`, on otherwise empty space two bots are filling voxels to stand one on another (e.g. one y = 0, second y = 1). Voxel 1 only becomes grounded at the end of the turn.
2. `S.harmonics == High', Voxel 1 is floating at y = 1. Robot 0 flips `harmonics` to `Low` and in the same tick Robot 1 fills the voxel under Voxel 1.

**Comment by MatthewFluet** [comment]
No, the groundness check only happens at the beginning of a step (and every step except the last has a next step that will check the groundedness).

With regards to the specific questions:
1. This scenario succeeds.
2. This scenario also succeeds.
