### ISSUE TITLE
Is the energy computation in the "Execute Trace" simulator correct?

### ISSUE THREAD

**Issue by cdadr** [icfpcontest2018/icfpcontest2018.github.io#7]
I am running the [Execute Trace](https://icfpcontest2018.github.io/lgtn/exec-trace.html) simulator for model 002. The "R" value in this model's file is 250. I am running the default trace file at speed 1/60 so I can see what's going on. After the first step (Flip), the energy used is 24020, which does not match the formula in the task description of `(3 * R * R * R) + (20 * n)` 

It looks like it's treating 'R' as 20, rather than 250 for the "global resonant subspace field" calculation. Am I missing something?

Cheers,
Mike

**Comment by MatthewFluet** [comment]
`LA002_tgt.mdl` has resolution 20 (not 250).  250 is the maximum resolution that a model may have.

**Comment by cdadr** [comment]
Whoops, I was looking at the wrong file... Thanks!
