### ISSUE TITLE
Flip by N robots resolution

### ISSUE THREAD

**Issue by lostmsu** [icfpcontest2018/icfpcontest2018.github.io#8]
Options:
1. conflict/error/invalid
2. any number of bots cause single flip
3. it flips if `n % 2 == 1` where `n` is the number of bots, performing `Flip`, otherwise it does not

**Comment by MatthewFluet** [comment]
Each bot that executes a `Flip` independently flips the harmonics.  So, option 3 (it flips if `n % 2 == 1` where `n` is the number of bots, performing `Flip`, otherwise it does not.)
