### ISSUE TITLE
How often the Live Standings are updated?

### ISSUE THREAD

**Issue by igorlukanin** [icfpcontest2018/icfpcontest2018.github.io#9]
It looks like it takes about 30 to 90 minutes for the [Live Standings](https://icfpcontest2018.github.io/lgtn/live-standings.html#team-0007) page to update. I'm not sure how ofter we should expect it to update...

**Comment by MatthewFluet** [comment]
The Live Standings (and Submissions Acks) are manual right now, watching for anomalies, but should be automated soon (and therefore more frequent).

**Comment by igorlukanin** [comment]
Oh, I see, thanks. I'm just eager to know how the last submission of Team kontur.ru affected its score.

**Comment by MatthewFluet** [comment]
Submission Acks and Live Standings should be automatically updating approximately every 15min.

**Comment by adept** [comment]
What about Live Standings for the main contest?

**Comment by MatthewFluet** [comment]
Coming soon to a website near you.

**Comment by MatthewFluet** [comment]
And there now.
